### ISSUE TITLE
[BUG] A glitchy gem generates named Error Gem

### ISSUE THREAD

**Issue by basugaming1** [ISeal-plugin-developement/PowerGems#11]
**Describe the bug**
When someone joins the server for the first time, very rarely he gets an error gem that it is glitched and after that, console starts spamming a whole lot of things.

**To Reproduce**
1. Upload the plugin.
2. Restart the server
3. Join the server
4. You will very rarely get that

**Expected behavior**
The player should get any of the gems that is listed on the wiki.

**Logs**
https://mclo.gs/9MmfKcr

**Server:**
 - OS: Ubuntu (idk much)
 - Software: Purpur
 - Plugin version: 3.5.0.3
 - Server logs ( provided above)

**Plugin output:**
 - Output of /d dump ( i don't have)
 - Addons loaded: none

**Comment by iseal56** [comment]
You know /d dump is a command right? Just execute it after you reproduce the issue and post the log here

**Comment by iseal56** [comment]
This has been fixed in v3.5.0.4
