### ISSUE TITLE
[FEATURE REQUEST] Gems Give Permanent effects

### ISSUE THREAD

**Issue by nothaiderrr** [ISeal-plugin-developement/PowerGems#14]
I wanted to tell you that if the gems give a permanent effect when held in off hand or main hand that would be nice
For Example:
Strength Gem Gives strength and sharpness on weapons as it levels up on he fifth upgrade it gives sharp 5
Fire gem Gives Fire resistance and fire aspect on level 2 it gives fire aspect 2 on level 3 it gives flame on bow on level 4 and 5 it gives some other cool feature
Sand Gem Gives Resistance 1 on first level and prot 1 on level 2, on all armor and so on as it gets levelled up prot 2 on level 3, prot 3 on level 4, prot 4 on level 5
And also a gem suggestion name Soul gem which has ability like spectator for 5 sec disabling other gems for 15 sec invisibility perm effect soul speed 1 on level 2, soul speed 2 and sweeping edge 1 on swords on level 3, soul speed 3 and sweeping edge 2  on level 4,sweeping edge 3 and swift sneak 3 on level 5
Also give unbreaking 3 ability to a gem like when gem held in off hand and item held in main hand it auto enchants it sorry if you have trouble reading this

**Comment by iseal56** [comment]
Please use the correct format.
