### ISSUE TITLE
[BUG] Strength gem ability not working

### ISSUE THREAD

**Issue by TheNoob5656** [ISeal-plugin-developement/PowerGems#28]
When I use the strength gem right click ability it only gives strength 2 and not saturation 2 and resistance 2
I even tried after upgrading my gem
Please fix it

**Comment by LunarcatOwO** [comment]
Report Invalid, the required information was not filled out.

**Comment by TheNoob5656** [comment]
sad

**Comment by TheNoob5656** [comment]
I will ask the owner to make the report

**Comment by LunarcatOwO** [comment]
Please tell him to provide the information as we need to reproduce the errors exactly
